[package]
name = "orkz"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "who I am"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
